export const FIGHT_TITLE = 'RUELLE FIGHTER II'
// Les mêmes caractéristiques sont utilisées en solo, en ligne et dans la sélection.
export const FIGHT_ROSTER = [
  { id: 'nova', name: 'RENO', asset: 'character-2', role: ["Bagarreur polyvalent", "All-round brawler"],
    strength: ["Équilibré, facile à maîtriser", "Balanced, easy to learn"],
    weakness: ["Aucune spécialité dominante", "No dominant specialty"],
    color: '#a8b796', dark: '#236177', light: '#b9fbff', accent: '#ffc967',
    speed: 115, power: 1, armor: 1, tempo: 1, reach: 1, jump: 355, regen: 7, plasmaCost: 35, plasmaSpeed: 250, plasmaPower: 1,
    stats: [3, 3, 3],
  },
  { id: 'vesper', name: 'VIOLETTE', asset: 'character-4', role: ["Acrobate de quartier", "Neighborhood acrobat"],
    strength: ["Coups rapides, grande mobilité", "Fast attacks, high mobility"],
    weakness: ["Fragile, coups moins puissants", "Fragile, lighter strikes"],
    color: '#d58dbc', dark: '#773652', light: '#ffe3ed', accent: '#ffe690',
    speed: 145, power: 0.85, armor: 1.15, tempo: 0.8, reach: 1, jump: 390, regen: 7, plasmaCost: 35, plasmaSpeed: 270, plasmaPower: 0.9,
    stats: [5, 2, 2],
  },
  { id: 'atlas', name: 'BIG BEN', asset: 'character-1', role: ["Poids lourd du ring", "Heavyweight boxer"],
    strength: ["Frappe lourde et défense solide", "Heavy strikes and solid defense"],
    weakness: ["Lent, récupération longue", "Slow, long recovery"],
    color: '#ef7b65', dark: '#765030', light: '#ffe9b2', accent: '#86f5ec',
    speed: 83, power: 1.35, armor: 0.78, tempo: 1.25, reach: 1.04, jump: 300, regen: 5, plasmaCost: 42, plasmaSpeed: 200, plasmaPower: 1.05,
    stats: [1, 5, 5],
  },
  { id: 'nyx', name: 'ONYX', asset: 'character-6', role: ["Ninja des ruelles", "Back-alley ninja"],
    strength: ["Sauts hauts, allonge et vitesse", "High jumps, reach and speed"],
    weakness: ["Fragile, spécial coûteux", "Fragile, expensive special"],
    color: '#cb6178', dark: '#413666', light: '#e2d4ff', accent: '#fa638f',
    speed: 138, power: 0.95, armor: 1.18, tempo: 0.9, reach: 1.14, jump: 420, regen: 5, plasmaCost: 42, plasmaSpeed: 290, plasmaPower: 0.85,
    stats: [5, 3, 1],
  },
  { id: 'helix', name: 'MAESTRO', asset: 'character-5', role: ["Sabreur mystique", "Mystic swordsman"],
    strength: ["Spécial puissant, énergie rapide", "Strong special, fast energy recovery"],
    weakness: ["Faible au corps à corps", "Weak at close range"],
    color: '#eac666', dark: '#2e6851', light: '#d1ffd5', accent: '#c8ff63',
    speed: 105, power: 0.75, armor: 1.08, tempo: 1, reach: 0.94, jump: 365, regen: 11, plasmaCost: 27, plasmaSpeed: 330, plasmaPower: 1.5,
    stats: [3, 2, 2],
  },
  { id: 'rook', name: 'LAME', asset: 'character-3', role: ["Duelliste impassible", "Unflappable duelist"],
    strength: ["Défense solide et longue portée", "Solid defense and long reach"],
    weakness: ["Attaques lentes, mobilité réduite", "Slow attacks, limited mobility"],
    color: '#a3d3dc', dark: '#713946', light: '#ffcab0', accent: '#8ce8ff',
    speed: 97, power: 1.1, armor: 0.88, tempo: 1.15, reach: 1.22, jump: 325, regen: 6, plasmaCost: 38, plasmaSpeed: 240, plasmaPower: 1.05,
    stats: [2, 4, 4],
  },
]
export const fighterProfile = id => FIGHT_ROSTER.find(f => f.id === id) ?? FIGHT_ROSTER[0]
export const isFighterId = id => FIGHT_ROSTER.some(f => f.id === id)
