// Les mêmes caractéristiques sont utilisées en solo, en ligne et dans la sélection.
export const FIGHT_ROSTER = [
  { id: 'nova', name: 'NOVA', role: ['Pilote polyvalent', 'All-round pilot'],
    strength: ['Arsenal équilibré, facile à maîtriser', 'Balanced arsenal, easy to learn'],
    weakness: ['Aucune spécialité dominante', 'No dominant specialty'],
    color: '#55e1ec', dark: '#236177', light: '#b9fbff', accent: '#ffc967', style: 'pilot',
    speed: 115, power: 1, armor: 1, tempo: 1, reach: 1, jump: 355, regen: 7, plasmaCost: 35, plasmaSpeed: 250, plasmaPower: 1,
    stats: [3, 3, 3],
  },
  { id: 'vesper', name: 'VESPER', role: ['Acrobate cybernétique', 'Cybernetic acrobat'],
    strength: ['Coups rapides, grande mobilité', 'Fast attacks, high mobility'],
    weakness: ['Fragile, coups moins puissants', 'Fragile, lighter strikes'],
    color: '#ff6da9', dark: '#773652', light: '#ffe3ed', accent: '#ffe690', style: 'acrobat',
    speed: 145, power: 0.85, armor: 1.15, tempo: 0.8, reach: 1, jump: 390, regen: 7, plasmaCost: 35, plasmaSpeed: 270, plasmaPower: 0.9,
    stats: [5, 2, 2],
  },
  { id: 'atlas', name: 'ATLAS', role: ['Colosse de chantier', 'Industrial juggernaut'],
    strength: ['Frappe lourde et blindage renforcé', 'Heavy strikes and reinforced armor'],
    weakness: ['Lent, récupération longue', 'Slow, long recovery'],
    color: '#f5b54e', dark: '#765030', light: '#ffe9b2', accent: '#86f5ec', style: 'heavy',
    speed: 83, power: 1.35, armor: 0.78, tempo: 1.25, reach: 1.04, jump: 300, regen: 5, plasmaCost: 42, plasmaSpeed: 200, plasmaPower: 1.05,
    stats: [1, 5, 5],
  },
  { id: 'nyx', name: 'NYX', role: ['Ombre des coursives', 'Corridor shadow'],
    strength: ['Sauts hauts, allonge et vitesse', 'High jumps, reach and speed'],
    weakness: ['Peu de blindage, plasma coûteux', 'Light armor, expensive plasma'],
    color: '#ac89ff', dark: '#413666', light: '#e2d4ff', accent: '#fa638f', style: 'ninja',
    speed: 138, power: 0.95, armor: 1.18, tempo: 0.9, reach: 1.14, jump: 420, regen: 5, plasmaCost: 42, plasmaSpeed: 290, plasmaPower: 0.85,
    stats: [5, 3, 1],
  },
  { id: 'helix', name: 'HELIX', role: ['Émissaire des Gardiens', 'Guardian emissary'],
    strength: ['Plasma puissant, énergie rapide', 'Strong plasma, fast energy recovery'],
    weakness: ['Faible au corps à corps', 'Weak at close range'],
    color: '#74e887', dark: '#2e6851', light: '#d1ffd5', accent: '#c8ff63', style: 'alien',
    speed: 105, power: 0.75, armor: 1.08, tempo: 1, reach: 0.94, jump: 365, regen: 11, plasmaCost: 27, plasmaSpeed: 330, plasmaPower: 1.5,
    stats: [3, 2, 2],
  },
  { id: 'rook', name: 'ROOK', role: ['Sentinelle mercenaire', 'Mercenary sentinel'],
    strength: ['Blindage solide et longue portée', 'Solid armor and long reach'],
    weakness: ['Attaques lentes, mobilité réduite', 'Slow attacks, limited mobility'],
    color: '#f16d59', dark: '#713946', light: '#ffcab0', accent: '#8ce8ff', style: 'sentinel',
    speed: 97, power: 1.1, armor: 0.88, tempo: 1.15, reach: 1.22, jump: 325, regen: 6, plasmaCost: 38, plasmaSpeed: 240, plasmaPower: 1.05,
    stats: [2, 4, 4],
  },
]
export const fighterProfile = id => FIGHT_ROSTER.find(f => f.id === id) ?? FIGHT_ROSTER[0]
export const isFighterId = id => FIGHT_ROSTER.some(f => f.id === id)
